### ISSUE TITLE
Documentation: Issue Working Guide 

### ISSUE THREAD

**Issue by pvvarun** [nodexpertsdev/RnD#64]
1. Create a separate file for Issue Guidelines.
2. Link it to the README [file](https://github.com/nodexpertsdev/RnD/blob/develop/README.md).

Anyone working on an issue should follow these guidelines:

1. Issue has an assignee.
2. Issue has a respective label.
3. Issue has a proper description.
4. Issues should be created, keeping in mind that its PR should have the least possible impact.

**Comment by gkgbunny** [comment]
Please add the following point:-
A label like **DONE** or **CLOSED** is added once the issue has been closed.
