### ISSUE TITLE
Validation error in Password field

### ISSUE THREAD

**Issue by aman-successive** [nodexpertsdev/RnD#77]
Password field is not accepting all of the special characters as valid.
Create a regex which can accept all the special characters.
Check the list of special characters from here: https://www.owasp.org/index.php/Password_special_characters
password must have at least 8 characters, at least 1 uppercase letter, at least 1 lowercase letter, at least 1 special char and at least 1 number

**Comment by DPDeepak** [comment]
please add assignee and label
